Content Based Recommendation

1. Import Libs

In [25]:
import pandas as pd
from scipy.io import arff
import numpy as np
import csv
import re

Loading Movies dataset

In [35]:
movies = pd.read_csv("movies.csv")
# movies = movies.iloc[:, 1:]  # Remove first column (ID)
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 722317 entries, 0 to 722316
Data columns (total 20 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   id                    722317 non-null  int64
 1   title                 722311 non-null  object
 2   genres                512000 non-null  object
 3   original_language     722317 non-null  object
 4   overview              604074 non-null  object
 5   popularity            722317 non-null  float64
 6   production_companies  337391 non-null  object
 7   release_date          670768 non-null  object
 8   budget                722317 non-null  float64
 9   revenue               722317 non-null  float64
 10  runtime               687982 non-null  float64
 11  status                722317 non-null  object
 12  tagline               108476 non-null  object
 13  vote_average          722317 non-null  float64
 14  vote_count            722317 non-null  float64
 15  credits               497603 non-null  object
 16  keywords              210639 non-null  object
 17  poster_path           537824 non-null  object
 18  backdrop_path         223211 non-null  object
 19  recommendations       36016 non-null   object
dtypes: float64(6), int64(1), object(13)
memory usage: 110.2+ MB

Review data

In [36]:
movies.head()

,id,title,genres,original_language,overview,popularity,production_companies,release_date,budget,revenue,runtime,status,tagline,vote_average,vote_count,credits,keywords,poster_path,backdrop_path,recommendations
0,615656,Meg 2: The Trench,Action-Science Fiction-Horror,en,An exploratory dive into the deepest depths of...,8763.998,Apelles Entertainment-Warner Bros. Pictures-di...,2023-08-02,129000000.0,3.520565e+08,116.0,Released,Back for seconds.,7.079,1365.0,Jason Statham-Wu Jing-Shuya Sophia Cai-Sergio ...,based on novel or book-sequel-kaiju,/4m1Au3YkjqsxF8iwQy0fPYSxE0h.jpg,/qlxy8yo5bcgUw2KAmmojUKp4rHd.jpg,1006462-298618-569094-1061181-346698-1076487-6...
1,758323,The Pope's Exorcist,Horror-Mystery-Thriller,en,Father Gabriele Amorth Chief Exorcist of the V...,5953.227,Screen Gems-2.0 Entertainment-Jesus & Mary-Wor...,2023-04-05,18000000.0,6.567582e+07,103.0,Released,Inspired by the actual files of Father Gabriel...,7.433,545.0,Russell Crowe-Daniel Zovatto-Alex Essoe-Franco...,spain-rome italy-vatican-pope-pig-possession-c...,/9JBEPLTPSm0d1mbEcLxULjJq9Eh.jpg,/hiHGRbyTcbZoLsYYkO4QiCLYe34.jpg,713704-296271-502356-1076605-1084225-1008005-9...
2,533535,Deadpool & Wolverine,Action-Comedy-Science Fiction,en,A listless Wade Wilson toils away in civilian ...,5410.496,Marvel Studios-Maximum Effort-21 Laps Entertai...,2024-07-24,200000000.0,1.326387e+09,128.0,Released,Come together.,7.765,3749.0,Ryan Reynolds-Hugh Jackman-Emma Corrin-Matthew...,hero-superhero-anti hero-mutant-breaking the f...,/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg,/dvBCdCohwWbsP5qAaglOXagDMtk.jpg,573435-519182-957452-1022789-945961-718821-103...
3,667538,Transformers: Rise of the Beasts,Action-Adventure-Science Fiction,en,When a new threat capable of destroying the en...,5409.104,Skydance-Paramount-di Bonaventura Pictures-Bay...,2023-06-06,200000000.0,4.070455e+08,127.0,Released,Unite or fall.,7.340,1007.0,Anthony Ramos-Dominique Fishback-Luna Lauren V...,peru-alien-end of the world-based on cartoon-b...,/gPbM0MK8CP8A174rmUwGsADNYKD.jpg,/woJbg7ZqidhpvqFGGMRhWQNoxwa.jpg,496450-569094-298618-385687-877100-598331-4628...
4,693134,Dune: Part Two,Science Fiction-Adventure,en,Follow the mythic journey of Paul Atreides as ...,4742.163,Legendary Pictures,2024-02-27,190000000.0,6.838137e+08,167.0,Released,Long live the fighters.,8.300,2770.0,Timothée Chalamet-Zendaya-Rebecca Ferguson-Jav...,epic-based on novel or book-fight-sandstorm-sa...,/czembW0Rk1Ke7lCJGahbOhdCuhV.jpg,/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg,438631-763215-792307-1011985-467244-634492-359...

Adding Columns name

In [37]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 722317 entries, 0 to 722316
Data columns (total 20 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   id                    722317 non-null  int64
 1   title                 722311 non-null  object
 2   genres                512000 non-null  object
 3   original_language     722317 non-null  object
 4   overview              604074 non-null  object
 5   popularity            722317 non-null  float64
 6   production_companies  337391 non-null  object
 7   release_date          670768 non-null  object
 8   budget                722317 non-null  float64
 9   revenue               722317 non-null  float64
 10  runtime               687982 non-null  float64
 11  status                722317 non-null  object
 12  tagline               108476 non-null  object
 13  vote_average          722317 non-null  float64
 14  vote_count            722317 non-null  float64
 15  credits               497603 non-null  object
 16  keywords              210639 non-null  object
 17  poster_path           537824 non-null  object
 18  backdrop_path         223211 non-null  object
 19  recommendations       36016 non-null   object
dtypes: float64(6), int64(1), object(13)
memory usage: 110.2+ MB

Features Selected :
1. Title
2. ID
3. Genre
4. Popularity
5. Revenue
6. Vote Avg
7. Vote Count
8. Overview

In [40]:
movies = movies[['title', 'id', 'genres', 'popularity', 'revenue', 'tagline', 'vote_average', 'vote_count', 'overview']]

In [41]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 722317 entries, 0 to 722316
Data columns (total 9 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   title         722311 non-null  object
 1   id            722317 non-null  int64
 2   genres        512000 non-null  object
 3   popularity    722317 non-null  float64
 4   revenue       722317 non-null  float64
 5   tagline       108476 non-null  object
 6   vote_average  722317 non-null  float64
 7   vote_count    722317 non-null  float64
 8   overview      604074 non-null  object
dtypes: float64(4), int64(1), object(4)
memory usage: 49.6+ MB

In [42]:
movies['genres'].isna().value_counts()

genres
False    512000
True     210317
Name: count, dtype: int64

In [43]:
movies.loc[movies['genres'].isna(), ['id', 'title', 'overview']].head(20)

,id,title,overview
173,287004,Avatar: Production Materials,Production material overview of what was used ...
309,860407,人妻性奴隶：美人妻调教日记,NaN
354,839706,BTS Japan Official Fanmeeting Vol.3: Reaching You,BTS Japan Official Fanmeeting Vol.3 ~Reaching ...
506,967493,Inside The Walking Dead Season 11 (Part 1),Join host Clarke Wolfe for the ultimate backst...
754,466353,Oppressive Torture,In the end of the 19th century social restorat...
1200,128785,"Calendar Girl, Cop, Killer? The Bambi Bembenek...",Story of attractive cop Laurencia Bembenek who...
1233,771709,Cuando te veo palpito,NaN
1390,897243,XXXMOG!,Mark is a director working in Taipei City who ...
1414,897243,XXXMOG!,Mark is a director working in Taipei City who ...
1484,946030,Onsen porno chitai,Nikkatsu Roman Porno
1501,646749,Yu Pui Tsuen,NaN
1575,185086,Office Lady Rope Slave,Two assistants to an S&M photographer decide t...
1587,796822,DRagON BALL P2 2wice dropda bbeet,FUK YOUtube :P
1734,796822,DRagON BALL P2 2wice dropda bbeet,FUK YOUtube :P
1794,788483,Hope,A short film set in Cyprus an island in the Me...
1899,796822,DRagON BALL P2 2wice dropda bbeet,FUK YOUtube :P
2135,631330,High School Girl Story Indecent Fruit,NaN
2323,902870,The Sniper,The Salvation Society is the most powerful cri...
2526,771709,Cuando te veo palpito,NaN
2557,340825,Beautiful Sisters: Strip!,Story of two beautiful sisters.